### ISSUE TITLE
Playing the same audioclip 2+ times in one frame causes a crash

### ISSUE THREAD

**Issue by daafu** [EinBurgbauer/Pile#3]
Playing the same audio clip causes a crash in SoLoud lib. Not sure if this is a bug in SoLoud lib, or in Pile. Ideally the sounds should be mixed together (increasing volume) or one of them dropped.

```using Pile;
using System;
using System.Collections;
using System.Threading;

[AlwaysInclude]
class PileTestGame : Game<PileTestGame>
{
	static this()
	{
		Core.Config.createGame = () => new PileTestGame();
		Core.Config.gameTitle = "Pile Test";
		Core.Config.windowTitle = "Pile Test";
	}

	public Asset<AudioClip> testSound;
	public GlobalSource audioSource = new .() ~ delete _;

	protected override void Startup()
	{
		Assets.LoadPackage("assets");

		testSound = Asset<AudioClip>("monster-10");
	}

	protected override void Shutdown()
	{
		Assets.UnloadPackage("assets");
	}

	protected override void Update()
	{
                // This casues a crash on the audio thread
		for (int i = 0; i < 2; i++) {
			audioSource.Play(testSound);
		}
	}
}
```

![image](https://user-images.githubusercontent.com/17444514/163734640-c46376f2-ab0e-49a3-866a-2cb2e5de82a6.png)

**Comment by EinScott** [comment]
I've reproduced this and will look into it. Currently i just call soloud to do stuff, maybe there's some sort of max_sound_count i need to manually enforce. It seems to be a general thing with playing lots of sounds (somewhere above 24 sounds currently playing it crashes...).

**Comment by EinScott** [comment]
The culprit seems to be the SetInaudibleBehaviour in SL_GlobalSource.bf:43. I'll look into a fix in the coming days, there are a number of related issues on the soloud github, i'll probably rebuild soloud for some of those fixes since the 2020 release and possibly some other fixes on the beef side.

For a quick fix, just comment that line out, the difference is negligable for GlobalSource anyway and it won't crash.

**Comment by EinScott** [comment]
Just upgrading alone doesn't fix it... i'll check to see if one of the fixes suggested in the soloud issues properly resolves it.

**Comment by EinScott** [comment]
The crash is fixed, though the behaviour has changed to soloud stock behaviour of pausing inaudible clips. We can revert that when it gets properly fixed, but for now with the amount of sounds playing globally for them to be cut off, it's probably not noticable anyway when things are properly set up.
